### PR TITLE
Cxx and julia compatibility

### PR DESCRIPTION
**Pull request by MaximeBouton**

### CODE REVIEW

**Comment by MaximeBouton** [comment]
@duncaneddy let's use that branch to troubleshoot issue #22

**Comment by MaximeBouton** [comment]
I tried to update the build_tarballs of Spot_julia_jll here: https://github.com/JuliaPackaging/Yggdrasil/pull/8707 
Not sure if that will help much.

**Comment by mykelk** [comment]
It looks like [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) is still using the older version of Spot?

**Comment by MaximeBouton** [comment]
@mykelk yes it is using an old version of Spot, we should update to the new version but I am thinking to do it one step at a time. It will be easier to get this version up and running, I think.

**Comment by mykelk** [comment]
Sounds good!

**Comment by mykelk** [comment]
This looks good to merge and tag!

**Comment by mykelk** [comment]
@JuliaRegistrator register

**Pull request merged**
